# Generated by Django 3.1.7 on 2021-02-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210222_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='design_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='montage_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='production_level',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Advanced', 'Advanced'), ('Profissional', 'Profissional')], default='Beginner', max_length=70),
        ),
    ]
