# Generated by Django 3.1.7 on 2021-02-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210223_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='domain',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
