# Generated by Django 3.1.7 on 2021-03-01 00:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='', upload_to=accounts.models.imageupload),
            preserve_default=False,
        ),
    ]
