# Generated by Django 3.1.7 on 2021-03-01 01:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=accounts.models.imageupload),
        ),
    ]
