# Generated by Django 3.1.7 on 2021-04-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210301_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
            ],
        ),
    ]
