# Generated by Django 3.1.7 on 2021-04-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_signupswitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupswitch',
            name='switch_type',
            field=models.CharField(default='main', max_length=70),
        ),
    ]
