# Generated by Django 3.1.7 on 2021-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(default='', max_length=100)),
                ('work_hours', models.CharField(default='', max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('facebook', models.URLField(max_length=300)),
                ('instagram', models.URLField(max_length=300)),
            ],
        ),
    ]
